/*
SQLyog Community
MySQL - 5.5.44-0+deb7u1-log : Database - m01msaccess03
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `tdta_csv_orders` */

CREATE TABLE `tdta_csv_orders` (
  `order id` varchar(255) NOT NULL DEFAULT '',
  `patient mis id` int(11) DEFAULT NULL,
  `order mis id` int(11) NOT NULL DEFAULT '0',
  `order diagnosis` mediumtext,
  `order problem` varchar(255) DEFAULT NULL,
  `order referral date` varchar(255) DEFAULT NULL,
  `order type` varchar(255) DEFAULT NULL,
  `order modality` varchar(255) DEFAULT NULL,
  `order exam type` varchar(255) DEFAULT NULL,
  `order priority` varchar(255) DEFAULT NULL,
  `order accounting` varchar(255) DEFAULT NULL,
  `order billing adress` varchar(255) DEFAULT NULL,
  `order billing adress name` varchar(255) DEFAULT NULL,
  `order billing adress street` varchar(255) DEFAULT NULL,
  `order billing adress street suffix` varchar(255) DEFAULT NULL,
  `order billing adress postalcode` varchar(255) DEFAULT NULL,
  `order billing adress city` varchar(255) DEFAULT NULL,
  `order billing adress country` varchar(255) DEFAULT NULL,
  `order agent` varchar(255) DEFAULT NULL,
  `order incasso` varchar(255) DEFAULT NULL,
  `order payment method` varchar(255) DEFAULT NULL,
  `order payment received` varchar(255) DEFAULT NULL,
  `order payment received date` varchar(255) DEFAULT NULL,
  `order location` varchar(255) DEFAULT NULL,
  `order device` varchar(255) DEFAULT NULL,
  `order date` varchar(255) DEFAULT NULL,
  `order time` varchar(255) DEFAULT NULL,
  `order duration` varchar(255) DEFAULT NULL,
  `order lead time` varchar(255) DEFAULT NULL,
  `order state` varchar(255) DEFAULT NULL,
  `order change cause` varchar(255) DEFAULT NULL,
  `order billing organization` varchar(255) DEFAULT NULL,
  `order reporting organization` varchar(255) DEFAULT NULL,
  `order reporting physician` varchar(255) DEFAULT NULL,
  `order referring organization` varchar(255) DEFAULT NULL,
  `order referring physician` varchar(255) DEFAULT NULL,
  `order referring organization comment` mediumtext,
  `order report transfer referring physician` varchar(255) DEFAULT NULL,
  `order treating organization` varchar(255) DEFAULT NULL,
  `order treating physician` varchar(255) DEFAULT NULL,
  `order report transfer treating physician` varchar(255) DEFAULT NULL,
  `report id` varchar(255) DEFAULT NULL,
  `report id ext` varchar(255) DEFAULT NULL,
  `report exam technique` mediumtext,
  `report contrast media` mediumtext,
  `report bodytext` mediumtext,
  `report summary` mediumtext,
  `report exam type` varchar(255) DEFAULT NULL,
  `report diagnosis` mediumtext,
  `report amnesis` mediumtext,
  `report modality` varchar(255) DEFAULT NULL,
  `report coils` varchar(255) DEFAULT NULL,
  `report date` varchar(255) DEFAULT NULL,
  `dt_DateCreated` datetime DEFAULT NULL,
  `order external organization` varchar(255) DEFAULT NULL,
  `order external id` varchar(255) DEFAULT NULL,
  `order external patient visit id` varchar(255) DEFAULT NULL,
  `report complication factors` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`order mis id`),
  KEY `order id` (`order id`),
  KEY `patient mis id` (`patient mis id`),
  KEY `order billing organization` (`order billing organization`),
  KEY `order referring organization` (`order referring organization`),
  KEY `order reporting physician` (`order reporting physician`),
  KEY `order date` (`order date`),
  KEY `idx_order_state` (`order state`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `tdta_csv_orderstates` */

CREATE TABLE `tdta_csv_orderstates` (
  `patient mis id` int(11) DEFAULT NULL,
  `order mis id` int(11) DEFAULT NULL,
  `state mis id` int(11) NOT NULL DEFAULT '0',
  `state number` int(11) DEFAULT NULL,
  `state group` varchar(255) DEFAULT NULL,
  `state current state` int(11) DEFAULT NULL,
  `state next state` int(11) DEFAULT NULL,
  `state next action` int(11) DEFAULT NULL,
  `state date` datetime DEFAULT NULL,
  `state user` varchar(255) DEFAULT NULL,
  `state comment` longtext,
  `dt_DateCreated` datetime DEFAULT NULL,
  PRIMARY KEY (`state mis id`),
  KEY `order mis id` (`order mis id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `tdta_csv_organizations` */

CREATE TABLE `tdta_csv_organizations` (
  `organization id` varchar(255) NOT NULL DEFAULT '',
  `organization mis id` varchar(255) NOT NULL DEFAULT '',
  `organization id ext orgname` varchar(255) DEFAULT NULL,
  `organization name` varchar(255) DEFAULT NULL,
  `organization additional name 1` varchar(255) DEFAULT NULL,
  `organization contact person` varchar(255) DEFAULT NULL,
  `organization field` varchar(255) DEFAULT NULL,
  `organization type` varchar(255) DEFAULT NULL,
  `organization number 1` varchar(255) DEFAULT NULL,
  `organization number 2` varchar(255) DEFAULT NULL,
  `organization address street` varchar(255) DEFAULT NULL,
  `organization address street suffix` varchar(255) DEFAULT NULL,
  `organization address postalcode` varchar(255) DEFAULT NULL,
  `organization address city` varchar(255) DEFAULT NULL,
  `organization address country` varchar(255) DEFAULT NULL,
  `organization telephone number 1` varchar(255) DEFAULT NULL,
  `organization telephone number 2` varchar(255) DEFAULT NULL,
  `organization telephone number fax` varchar(255) DEFAULT NULL,
  `organization e-mail 1` varchar(255) DEFAULT NULL,
  `organization e-mail 2` varchar(255) DEFAULT NULL,
  `organization report transfer email` varchar(255) DEFAULT NULL,
  `organization report transfer fax` varchar(255) DEFAULT NULL,
  `organization report transfer letter` varchar(255) DEFAULT NULL,
  `organization comment` varchar(255) DEFAULT NULL,
  `organization medneo role` varchar(255) DEFAULT NULL,
  `dt_DateCreated` datetime DEFAULT NULL,
  PRIMARY KEY (`organization mis id`),
  KEY `organization id` (`organization id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `tdta_csv_patients` */

CREATE TABLE `tdta_csv_patients` (
  `patient id` varchar(255) NOT NULL DEFAULT '',
  `patient mis id` int(11) NOT NULL DEFAULT '0',
  `patient sex` varchar(255) DEFAULT NULL,
  `patient name title` varchar(255) DEFAULT NULL,
  `patient first name` varchar(255) DEFAULT NULL,
  `patient name prefix` varchar(255) DEFAULT NULL,
  `patient name` varchar(255) DEFAULT NULL,
  `patient name suffix` varchar(255) DEFAULT NULL,
  `patient date of birth` varchar(255) DEFAULT NULL,
  `patient guardian` varchar(255) DEFAULT NULL,
  `patient address street` varchar(255) DEFAULT NULL,
  `patient address street suffix` varchar(255) DEFAULT NULL,
  `patient address postalcode` varchar(255) DEFAULT NULL,
  `patient address city` varchar(255) DEFAULT NULL,
  `patient address country` varchar(255) DEFAULT NULL,
  `patient underwriter type` varchar(255) DEFAULT NULL,
  `patient covered service type` varchar(255) DEFAULT NULL,
  `patient underwriter organization name` varchar(255) DEFAULT NULL,
  `patient underwriter organization ID` varchar(255) DEFAULT NULL,
  `patient covered party id` varchar(255) DEFAULT NULL,
  `patient covered party id 2` varchar(255) DEFAULT NULL,
  `patient covered party state` varchar(255) DEFAULT NULL,
  `patient covered party state 2` varchar(255) DEFAULT NULL,
  `patient assigned device effective time` varchar(255) DEFAULT NULL,
  `patient covered party card reading date` varchar(255) DEFAULT NULL,
  `patient covered party card reading info` varchar(255) DEFAULT NULL,
  `patient identity card` varchar(255) DEFAULT NULL,
  `patient identity card id` varchar(255) DEFAULT NULL,
  `patient telephone number privat` varchar(255) DEFAULT NULL,
  `patient telephone number business` varchar(255) DEFAULT NULL,
  `patient telephone number mobile` varchar(255) DEFAULT NULL,
  `patient telephone number fax` varchar(255) DEFAULT NULL,
  `patient e-mail 1` varchar(255) DEFAULT NULL,
  `patient e-mail 2` varchar(255) DEFAULT NULL,
  `dt_DateCreated` datetime DEFAULT NULL,
  `patient external organization` varchar(255) DEFAULT NULL,
  `patient external id` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`patient mis id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `tdta_csv_physicians` */

CREATE TABLE `tdta_csv_physicians` (
  `physician id` varchar(255) DEFAULT NULL,
  `physician mis id` varchar(255) NOT NULL DEFAULT '',
  `physician id ext orgname` varchar(255) DEFAULT NULL,
  `physician name title` varchar(255) DEFAULT NULL,
  `physician name prefix` varchar(255) DEFAULT NULL,
  `physician name suffix` varchar(255) DEFAULT NULL,
  `physician name` varchar(255) DEFAULT NULL,
  `physician first name` varchar(255) DEFAULT NULL,
  `physician number` varchar(255) DEFAULT NULL,
  `physician sex` varchar(255) DEFAULT NULL,
  `physician address street` varchar(255) DEFAULT NULL,
  `physician address street suffix` varchar(255) DEFAULT NULL,
  `physician address postalcode` varchar(255) DEFAULT NULL,
  `physician address city` varchar(255) DEFAULT NULL,
  `physician address country` varchar(255) DEFAULT NULL,
  `physician field` varchar(255) DEFAULT NULL,
  `physician specialization` varchar(255) DEFAULT NULL,
  `physician comment` varchar(255) DEFAULT NULL,
  `physician medneo role` varchar(255) DEFAULT NULL,
  `physician telephone number privat` varchar(255) DEFAULT NULL,
  `physician telephone number business` varchar(255) DEFAULT NULL,
  `physician telephone number mobile` varchar(255) DEFAULT NULL,
  `physician telephone number fax` varchar(255) DEFAULT NULL,
  `physician e-mail 1` varchar(255) DEFAULT NULL,
  `physician e-mail 2` varchar(255) DEFAULT NULL,
  `physician_username` varchar(255) DEFAULT NULL,
  `dt_DateCreated` datetime DEFAULT NULL,
  PRIMARY KEY (`physician mis id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `tdta_csv_studies` */

CREATE TABLE `tdta_csv_studies` (
  `exam mis id` int(11) NOT NULL DEFAULT '0',
  `exam id` varchar(255) DEFAULT NULL,
  `patient mis id` int(11) DEFAULT NULL,
  `order mis id` int(11) DEFAULT NULL,
  `exam region` varchar(255) DEFAULT NULL,
  `exam type` varchar(255) DEFAULT NULL,
  `exam program` varchar(255) DEFAULT NULL,
  `exam contrast media` varchar(255) DEFAULT NULL,
  `exam duration` varchar(255) DEFAULT NULL,
  `dt_DateCreated` datetime DEFAULT NULL,
  `dt_DateUpdated` datetime DEFAULT NULL,
  PRIMARY KEY (`exam mis id`),
  KEY `patient mis id` (`patient mis id`),
  KEY `order mis id` (`order mis id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `tdta_invoices` */

CREATE TABLE `tdta_invoices` (
  `invoice_id` int(11) NOT NULL,
  `invoice_patient_id` int(11) DEFAULT NULL,
  `invoice_insurance_name` varchar(255) DEFAULT NULL,
  `invoice_insurance_nr` varchar(255) DEFAULT NULL,
  `invoice_insurance_tarif` varchar(255) DEFAULT NULL,
  `invoice_covered_party_nr` varchar(255) DEFAULT NULL,
  `invoice_covered_party_state` smallint(6) DEFAULT NULL,
  `invoice_covered_party_state_ext` varchar(255) DEFAULT NULL,
  `invoice_patient_assigned_device_effective_time` varchar(255) DEFAULT NULL,
  `invoice_patient_covered_party_card_reading_date` varchar(255) DEFAULT NULL,
  `invoice_recipient_type` varchar(255) DEFAULT NULL,
  `invoice_recipient_org_name` varchar(255) DEFAULT NULL,
  `invoice_recipient_salutation` varchar(255) DEFAULT NULL,
  `invoice_recipient_name_title` varchar(255) DEFAULT NULL,
  `invoice_recipient_name` varchar(255) DEFAULT NULL,
  `invoice_recipient_first_name` varchar(255) DEFAULT NULL,
  `invoice_recipient_street` varchar(255) DEFAULT NULL,
  `invoice_recipient_street_suffix` varchar(255) DEFAULT NULL,
  `invoice_recipient_plz` varchar(255) DEFAULT NULL,
  `invoice_recipient_city` varchar(255) DEFAULT NULL,
  `invoice_recipient_country` varchar(255) DEFAULT NULL,
  `invoice_bg_name` varchar(255) DEFAULT NULL,
  `invoice_bg_ik` varchar(255) DEFAULT NULL,
  `invoice_bg_heilbehandlung` varchar(255) DEFAULT NULL,
  `invoice_bg_unfalltag` datetime DEFAULT NULL,
  `invoice_order_accounting` varchar(255) DEFAULT NULL,
  `invoice_billing_organization_id` varchar(255) DEFAULT NULL,
  `invoice_referral_quartal` int(11) DEFAULT NULL,
  `invoice_referral_date` datetime DEFAULT NULL,
  `invoice_referring_organization_id` varchar(255) DEFAULT NULL,
  `invoice_referring_physician_id` varchar(255) DEFAULT NULL,
  `invoice_referrer_bsnr` varchar(255) DEFAULT NULL,
  `invoice_referrer_lanr` varchar(255) DEFAULT NULL,
  `invoice_date` datetime DEFAULT NULL,
  `invoice_diagnose` mediumtext,
  `invoice_auftrag` varchar(255) DEFAULT NULL,
  `invoice_cashing` varchar(255) DEFAULT NULL,
  `invoice_billing_org_medneo_split` double(5,4) DEFAULT NULL,
  `invoice_export_date` datetime DEFAULT NULL,
  `invoice_backoffice_comment` mediumtext,
  `invoice_agency_costs` double(5,2) DEFAULT NULL,
  `invoice_state` smallint(6) DEFAULT NULL,
  `invoice_type` varchar(10) NOT NULL DEFAULT '',
  `invoice_cancellation_reference` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`invoice_id`),
  KEY `invoice_patient_id` (`invoice_patient_id`),
  KEY `invoice_order_accounting` (`invoice_order_accounting`),
  KEY `invoice_billing_organization_id` (`invoice_billing_organization_id`),
  KEY `invoice_referring_organization_id` (`invoice_referring_organization_id`),
  KEY `invoice_referring_physician_id` (`invoice_referring_physician_id`),
  KEY `invoice_referrer_bsnr` (`invoice_referrer_bsnr`),
  KEY `invoice_referrer_lanr` (`invoice_referrer_lanr`),
  KEY `invoice_state` (`invoice_state`),
  KEY `invoice_cancellation_reference` (`invoice_cancellation_reference`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `tdta_invoices_orders` */

CREATE TABLE `tdta_invoices_orders` (
  `invoice_id` int(11) NOT NULL,
  `order_id` varchar(255) NOT NULL,
  PRIMARY KEY (`invoice_id`,`order_id`),
  KEY `invoice_id` (`invoice_id`),
  KEY `order_id` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `tdta_keyorgphysicians` */

CREATE TABLE `tdta_keyorgphysicians` (
  `keyOrgPhysicians_id` int(11) NOT NULL AUTO_INCREMENT,
  `organization id` varchar(255) DEFAULT NULL,
  `physician id` varchar(255) DEFAULT NULL,
  `ris_physician_assignment_id` varchar(40) DEFAULT NULL COMMENT 'RISv2 PhysicianAssignment entity identifier',
  `ris_organization_site_id` varchar(40) DEFAULT NULL COMMENT 'RISv2 OrganizationSite entity identifier',
  `ris_physician_id` varchar(40) DEFAULT NULL COMMENT 'RISv2 Physician entity identifier',
  PRIMARY KEY (`keyOrgPhysicians_id`),
  KEY `organization id` (`organization id`),
  KEY `physician id` (`physician id`),
  KEY `ris_physician_assignment_id` (`ris_physician_assignment_id`),
  KEY `ris_organization_site_id` (`ris_organization_site_id`),
  KEY `ris_physician_id` (`ris_physician_id`)
) ENGINE=InnoDB AUTO_INCREMENT=13494 DEFAULT CHARSET=utf8;

/*Table structure for table `tdta_xml_organization` */

CREATE TABLE `tdta_xml_organization` (
  `organization_tmp id` int(11) DEFAULT NULL,
  `organization id` varchar(255) NOT NULL DEFAULT '',
  `organization mis id` varchar(255) DEFAULT NULL,
  `organization LDAP group` varchar(255) DEFAULT NULL,
  `organization id ext orgname` varchar(255) DEFAULT NULL,
  `organization name` varchar(255) DEFAULT NULL,
  `organization longname` varchar(255) DEFAULT NULL,
  `organization description` varchar(255) DEFAULT NULL,
  `organization contact person` varchar(255) DEFAULT NULL,
  `organization field` varchar(255) DEFAULT NULL,
  `organization type` varchar(255) DEFAULT NULL,
  `organization number 1` varchar(255) DEFAULT NULL,
  `organization number 2` varchar(255) DEFAULT NULL,
  `organization address street name` varchar(255) DEFAULT NULL,
  `organization address street number` varchar(255) DEFAULT NULL,
  `organization address street suffix` varchar(255) DEFAULT NULL,
  `organization address postalcode` varchar(255) DEFAULT NULL,
  `organization address city` varchar(255) DEFAULT NULL,
  `organization address country` varchar(255) DEFAULT NULL,
  `organization telephone number 1 prefix` varchar(255) DEFAULT NULL,
  `organization telephone number 1 number` varchar(255) DEFAULT NULL,
  `organization telephone number 2 prefix` varchar(255) DEFAULT NULL,
  `organization telephone number 2 number` varchar(255) DEFAULT NULL,
  `organization telephone number fax prefix` varchar(255) DEFAULT NULL,
  `organization telephone number fax number` varchar(255) DEFAULT NULL,
  `organization e-mail 1` varchar(255) DEFAULT NULL,
  `organization e-mail 2` varchar(255) DEFAULT NULL,
  `organization report transfer email` bit(1) DEFAULT b'0',
  `organization report transfer fax` bit(1) DEFAULT b'0',
  `organization report transfer letter` bit(1) DEFAULT b'0',
  `organization comment` varchar(255) DEFAULT NULL,
  `organization medneo role` varchar(255) DEFAULT NULL,
  `dt_MisScript` bit(1) DEFAULT b'0',
  `dt_DateCreated` varchar(40) DEFAULT NULL,
  `dt_MisScriptLastRunType` varchar(255) DEFAULT NULL,
  `dt_MisScriptLastRunDate` varchar(40) DEFAULT NULL,
  `dt_MisScriptLastRunUser` varchar(255) DEFAULT NULL,
  `organization report transfer email adress` varchar(255) DEFAULT NULL,
  `organziation e-mail password` varchar(255) DEFAULT NULL,
  `deactivation` int(1) DEFAULT '0',
  `organization_inkasso` varchar(10) NOT NULL DEFAULT 'PRAXIS',
  `logo_path` varchar(512) DEFAULT NULL,
  `organization id master` varchar(255) DEFAULT NULL,
  `migrate` int(1) DEFAULT NULL,
  `migrate_info` varchar(255) DEFAULT NULL,
  `ris_organization_site_id` varchar(40) DEFAULT NULL COMMENT 'RISv2 OrganizationSite entity identifier',
  `ris_organization_site_address_id` varchar(40) DEFAULT NULL COMMENT 'RISv2 OrganizationSiteAddress entity identifier',
  `ris_organization_id` varchar(40) DEFAULT NULL COMMENT 'Identifier of parent RISv2 Organization entity.',
  PRIMARY KEY (`organization id`),
  KEY `organization mis id` (`organization mis id`),
  KEY `organization name` (`organization name`),
  KEY `ris_organization_site_id` (`ris_organization_site_id`),
  KEY `ris_organization_site_address_id` (`ris_organization_site_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `tdta_xml_physicians` */

CREATE TABLE `tdta_xml_physicians` (
  `physician id` varchar(255) NOT NULL DEFAULT '',
  `physician mis id` varchar(255) DEFAULT NULL,
  `physician id ext orgname` varchar(255) DEFAULT NULL,
  `physician LDAP group` varchar(255) DEFAULT NULL,
  `physician LDAP user` varchar(255) DEFAULT NULL,
  `dt_MisScript` bit(1) DEFAULT b'0',
  `physician name title` varchar(255) DEFAULT NULL,
  `physician name prefix` varchar(255) DEFAULT NULL,
  `physician name suffix` varchar(255) DEFAULT NULL,
  `physician name` varchar(255) DEFAULT NULL,
  `physician first name` varchar(255) DEFAULT NULL,
  `physician number` varchar(255) DEFAULT NULL,
  `physician sex` varchar(255) DEFAULT NULL,
  `physician dateofbirth` varchar(255) DEFAULT NULL,
  `physician address street name` varchar(255) DEFAULT NULL,
  `physician address street number` varchar(255) DEFAULT NULL,
  `physician address street suffix` varchar(255) DEFAULT NULL,
  `physician address postalcode` varchar(255) DEFAULT NULL,
  `physician address city` varchar(255) DEFAULT NULL,
  `physician address country` varchar(255) DEFAULT NULL,
  `physician field` varchar(255) DEFAULT NULL,
  `physician specialization` varchar(255) DEFAULT NULL,
  `physician comment` varchar(255) DEFAULT NULL,
  `physician medneo role` varchar(255) DEFAULT NULL,
  `physician telephone number privat prefix` varchar(255) DEFAULT NULL,
  `physician telephone number privat number` varchar(255) DEFAULT NULL,
  `physician telephone number business prefix` varchar(255) DEFAULT NULL,
  `physician telephone number business number` varchar(255) DEFAULT NULL,
  `physician telephone number mobile prefix` varchar(255) DEFAULT NULL,
  `physician telephone number mobile number` varchar(255) DEFAULT NULL,
  `physician telephone number fax prefix` varchar(255) DEFAULT NULL,
  `physician telephone number fax number` varchar(255) DEFAULT NULL,
  `physician e-mail 1` varchar(255) DEFAULT NULL,
  `physician e-mail 2` varchar(255) DEFAULT NULL,
  `dt_DateCreated` datetime DEFAULT NULL,
  `dt_MisScriptLastRunType` varchar(255) DEFAULT NULL,
  `dt_MisScriptLastRunDate` datetime DEFAULT NULL,
  `dt_MisScriptLastRunUser` varchar(255) DEFAULT NULL,
  `migrate` int(1) DEFAULT NULL,
  `migrate_info` varchar(255) DEFAULT NULL,
  `ris_physician_id` varchar(40) DEFAULT NULL COMMENT 'RISv2 Physician entity identifier',
  `ris_physician_address_id` varchar(40) DEFAULT NULL COMMENT 'RISv2 PhysicianAddress entity identifier',
  `deactivate` int(1) NOT NULL DEFAULT '0' COMMENT 'values: 0 = active; 1 = inactive',
  PRIMARY KEY (`physician id`),
  KEY `physician name` (`physician name`),
  KEY `physician mis id` (`physician mis id`),
  KEY `ris_physician_id` (`ris_physician_id`),
  KEY `ris_physician_address_id` (`ris_physician_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
