package com.medneo.hdf5;

/**
 * Created by Jonathan on 23 Sep, 2018
 */
public class Image {
    //private int image_id;...This is autogenerated by DB
    private Object image;
    private String image_position;
    private String image_orientation;
    private double smallest_image_pixel_value;
    private double largest_image_pixel_value;
    private int series_id;
    private int study_id;
    private int patient_id;
    private String patient_id_diag;

    public Image(Object image, String image_position, String image_orientation, double smallest_image_pixel_value, double largest_image_pixel_value, int series_id, int study_id, int patient_id, String patient_id_diag) {
        this.image = image;
        this.image_position = image_position;
        this.image_orientation = image_orientation;
        this.smallest_image_pixel_value = smallest_image_pixel_value;
        this.largest_image_pixel_value = largest_image_pixel_value;
        this.series_id = series_id;
        this.study_id = study_id;
        this.patient_id = patient_id;
        this.patient_id_diag = patient_id_diag;
    }

    public Object getImage() {
        return image;
    }

    public void setImage(Object image) {
        this.image = image;
    }

    public String getImage_position() {
        return image_position;
    }

    public void setImage_position(String image_position) {
        this.image_position = image_position;
    }

    public String getImage_orientation() {
        return image_orientation;
    }

    public void setImage_orientation(String image_orientation) {
        this.image_orientation = image_orientation;
    }

    public double getSmallest_image_pixel_value() {
        return smallest_image_pixel_value;
    }

    public void setSmallest_image_pixel_value(double smallest_image_pixel_value) {
        this.smallest_image_pixel_value = smallest_image_pixel_value;
    }

    public double getLargest_image_pixel_value() {
        return largest_image_pixel_value;
    }

    public void setLargest_image_pixel_value(double largest_image_pixel_value) {
        this.largest_image_pixel_value = largest_image_pixel_value;
    }

    public int getSeries_id() {
        return series_id;
    }

    public void setSeries_id(int series_id) {
        this.series_id = series_id;
    }

    public int getStudy_id() {
        return study_id;
    }

    public void setStudy_id(int study_id) {
        this.study_id = study_id;
    }

    public int getPatient_id() {
        return patient_id;
    }

    public void setPatient_id(int patient_id) {
        this.patient_id = patient_id;
    }

    public String getPatient_id_diag() {
        return patient_id_diag;
    }

    public void setPatient_id_diag(String patient_id_diag) {
        this.patient_id_diag = patient_id_diag;
    }
}