package com.medneo.hdf5;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 * Created by Jonathan on 23 Sep, 2018
 */
public class ImageDaoImpl implements ImageDao {

    Connection connection = DBConnection.getConnection();

    @Override
    public boolean insertImage(Image image) {

        try{
            String sql = "INSERT INTO study VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement preparedStatement = connection.prepareStatement(sql);

            preparedStatement.setInt(1, 0); //used as a placeholder for iamge_id - autogenerated
            preparedStatement.setObject(2, image.getImage());
            preparedStatement.setString(3, image.getImage_position());
            preparedStatement.setString(4, image.getImage_orientation());
            preparedStatement.setDouble(5, image.getSmallest_image_pixel_value());
            preparedStatement.setDouble(6, image.getLargest_image_pixel_value());
            preparedStatement.setInt(7, image.getSeries_id());
            preparedStatement.setInt(8, image.getPatient_id());
            preparedStatement.setString(9, image.getPatient_id_diag());

            preparedStatement.executeUpdate();


        }
        catch (SQLException se){
            se.printStackTrace();
        }

        return false;
    }
}