package com.medneo.hdf5;

/**
 * Created by Jonathan on 09 Sep, 2018
 */
public class Study {

    private String studyInstanceUid;
    private int studyDate;
    private int studyTime;
    private String studyDescription;
    private String bodyPartExamined;
    private int patientID;  //autoGenerated ID in patient table
    private String patientIdDiag;

    public Study(String studyInstanceUid, int studyDate, int studyTime, String studyDescription, String bodyPartExamined, int patientID, String patientIdDiag) {
        this.studyInstanceUid = studyInstanceUid;
        this.studyDate = studyDate;
        this.studyTime = studyTime;
        this.studyDescription = studyDescription;
        this.bodyPartExamined = bodyPartExamined;
        this.patientID = patientID;
        this.patientIdDiag = patientIdDiag;
    }

    public String getStudyInstanceUid() {
        return studyInstanceUid;
    }

    public void setStudyInstanceUid(String studyInstanceUid) {
        this.studyInstanceUid = studyInstanceUid;
    }

    public int getStudyDate() {
        return studyDate;
    }

    public void setStudyDate(int studyDate) {
        this.studyDate = studyDate;
    }

    public int getStudyTime() {
        return studyTime;
    }

    public void setStudyTime(int studyTime) {
        this.studyTime = studyTime;
    }

    public String getStudyDescription() {
        return studyDescription;
    }

    public void setStudyDescription(String studyDescription) {
        this.studyDescription = studyDescription;
    }

    public String getBodyPartExamined() {
        return bodyPartExamined;
    }

    public void setBodyPartExamined(String bodyPartExamined) {
        this.bodyPartExamined = bodyPartExamined;
    }

    public int getPatientID() {
        return patientID;
    }

    public void setPatientID(int patientID) {
        this.patientID = patientID;
    }

    public String getPatientIdDiag() {
        return patientIdDiag;
    }

    public void setPatientIdDiag(String patientIdDiag) {
        this.patientIdDiag = patientIdDiag;
    }
}